// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFCoreDBFirstDemo.Models;

public partial class EmployeeProfile
{
    [Key]
    public int EmployeeId { get; set; }

    [StringLength(50)]
    public string MyProfile { get; set; }

    [ForeignKey("EmployeeId")]
    [InverseProperty("EmployeeProfile")]
    public virtual Employee Employee { get; set; }
}